import type { Metadata } from "next"; 
import { Noto_Sans, Roboto } from 'next/font/google';
import "./styles/reset.scss"
import "./globals.css";
import "./styles/common.scss";  
import CommonLayout from './components/CommonLayout';

const notoSans = Noto_Sans({ 
  subsets: ['latin'], 
  weight: ['100', '200', '300', '400', '500', '700', '800', '900'],
  variable: '--font-noto-sans',
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "next calorie app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={`${notoSans.variable} ${roboto.variable} ${notoSans.className}`}>   
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
