import type { Metadata } from "next"; 
import { Noto_Sans } from 'next/font/google' 
import "./styles/reset.scss"
import "./globals.css";
import "./styles/common.scss";  

const inter = Noto_Sans({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '700', '800', '900'] })
export const metadata: Metadata = {
  title: "next calorie app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={`${inter.className}`}>   
        {children}
      </body>
    </html>
  );
}
